// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kK60277DEL2exgG97S9Pwhishu3d3lw',
    appId: '1:622421696156:web:ae73f52fabc02b53781759',
    messagingSenderId: '622421696156',
    projectId: 'parkingcarapp-ef7de',
    authDomain: 'parkingcarapp-ef7de.firebaseapp.com',
    storageBucket: 'parkingcarapp-ef7de.appspot.com',
    measurementId: 'G-EW82BR40WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrX5ni-Lonj3pFc0CGdVmeYBVeATOliYw',
    appId: '1:622421696156:android:8cbcaf0cde6ff12a781759',
    messagingSenderId: '622421696156',
    projectId: 'parkingcarapp-ef7de',
    storageBucket: 'parkingcarapp-ef7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0lrabw0ju7RJeTxCHvimT5X_bZCl1Keo',
    appId: '1:622421696156:ios:a6aa37a594353c1f781759',
    messagingSenderId: '622421696156',
    projectId: 'parkingcarapp-ef7de',
    storageBucket: 'parkingcarapp-ef7de.appspot.com',
    iosBundleId: 'com.example.parkingCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0lrabw0ju7RJeTxCHvimT5X_bZCl1Keo',
    appId: '1:622421696156:ios:c747de8949b19e5d781759',
    messagingSenderId: '622421696156',
    projectId: 'parkingcarapp-ef7de',
    storageBucket: 'parkingcarapp-ef7de.appspot.com',
    iosBundleId: 'com.example.parkingCarApp.RunnerTests',
  );
}
